import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const loading=document.querySelector('#loading');
try { start(); } catch(e) { loading.hidden=false; loading.textContent='This scene needs WebGL 2. Try a browser with hardware acceleration enabled.'; console.error(e); }
function start(){
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0x8cbcc7);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x9cc4ca,.00014);
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,1,18000);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=45;controls.maxDistance=4800;controls.maxPolarAngle=Math.PI*.485;controls.panSpeed=.8;
scene.add(new THREE.HemisphereLight(0xc7e9ff,0x6d7350,2));
const sun=new THREE.DirectionalLight(0xffe4b5,3.1);sun.position.set(-1100,1600,700);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-1600,right:1600,top:1400,bottom:-1400,near:10,far:4200});sun.shadow.normalBias=2;sun.shadow.bias=-.0002;scene.add(sun);
const sky=new THREE.Mesh(new THREE.SphereGeometry(13000,32,20),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;void main(){float h=normalize(v).y;vec3 col=mix(vec3(.69,.82,.83),vec3(.19,.48,.68),pow(max(h,0.),.5));gl_FragColor=vec4(col,1.);}' }));scene.add(sky);
const fract=x=>x-Math.floor(x),mix=(a,b,t)=>a+(b-a)*t,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
function hash(x,z){return fract(Math.sin(x*127.1+z*311.7)*43758.5453)}
function noise(x,z){const i=Math.floor(x),j=Math.floor(z);let u=fract(x),v=fract(z);u=u*u*(3-2*u);v=v*v*(3-2*v);return mix(mix(hash(i,j),hash(i+1,j),u),mix(hash(i,j+1),hash(i+1,j+1),u),v)}
function fbm(x,z){return noise(x,z)*.55+noise(x*2.07+13,z*2.07)*.27+noise(x*4.13,z*4.13+3)*.12+noise(x*8.21,z*8.21)*.06}
function ellipse(x,z,cx,cz,rx,rz){return (1-Math.hypot((x-cx)/rx,(z-cz)/rz))*Math.min(rx,rz)}
function distance(x,z){const edge=(fbm(x*.007,z*.007)-.5)*95;let d=Math.min(ellipse(x,z,-80,-200,1210,970),-ellipse(x,z,120,320,740,760));for(const a of [[-830,850,115,180],[720,830,125,200],[510,1100,80,115],[-460,1170,58,77]])d=Math.max(d,ellipse(x,z,...a));return d+edge;}
function height(x,z){let d=distance(x,z);if(d<0)return -Math.min(110,Math.pow(-d,.88)*.6);let rise=clamp(d/90);rise=rise*rise*(3-2*rise);const peak=(cx,cz,r,h)=>h*Math.exp(-((x-cx)**2+(z-cz)**2)/(r*r));let mountains=peak(-650,-410,350,350)+peak(180,-790,320,420)+peak(880,-150,250,255)+peak(-950,330,220,190);let rugged=(fbm(x*.012,z*.012)-.4)*120+Math.abs(noise(x*.027,z*.027)-.5)*50;return d*.035+rise*(22+mountains+Math.max(-15,rugged));}
const size=4000,segments=400,geo=new THREE.PlaneGeometry(size,size,segments,segments);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position,colors=new Float32Array(pos.count*3);const sand=new THREE.Color('#d7c594'),green=new THREE.Color('#527440'),rock=new THREE.Color('#8a8875');
for(let i=0;i<pos.count;i++){let x=pos.getX(i),z=pos.getZ(i),h=height(x,z);pos.setY(i,h);const slope=Math.hypot(height(x+5,z)-height(x-5,z),height(x,z+5)-height(x,z-5))/10;let c=sand.clone().lerp(green,clamp((h-4)/19));c.lerp(rock,clamp((slope-.48)*1.4+Math.max(0,h-270)/180));c.multiplyScalar(.85+fbm(x*.08,z*.08)*.3);c.toArray(colors,i*3)}geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.computeVertexNormals();
const landMaterial=new THREE.MeshStandardMaterial({vertexColors:true,roughness:1});landMaterial.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 terrainPos;').replace('#include <begin_vertex>','#include <begin_vertex>\nterrainPos=position;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 terrainPos;\nfloat grain(vec3 p){return fract(sin(dot(p,vec3(12.9898,78.233,39.346)))*43758.5453);}').replace('#include <color_fragment>','#include <color_fragment>\nfloat stratum=sin(terrainPos.y*.9+sin(terrainPos.x*.035)*3.+sin(terrainPos.z*.04));diffuseColor.rgb *= .92+.08*stratum+.1*(grain(floor(terrainPos*2.))-.5);');};
const land=new THREE.Mesh(geo,landMaterial);land.receiveShadow=true;land.castShadow=true;scene.add(land);
// Bathymetry matches the visible terrain, including the shallow shelves.
const depthSize=512,depthData=new Uint8Array(depthSize*depthSize*4);for(let j=0;j<depthSize;j++)for(let i=0;i<depthSize;i++){const h=height((i/(depthSize-1)-.5)*size,(j/(depthSize-1)-.5)*size),k=(j*depthSize+i)*4;depthData[k]=clamp(-h/110)*255;depthData[k+1]=depthData[k+2]=depthData[k];depthData[k+3]=255}const depthMap=new THREE.DataTexture(depthData,depthSize,depthSize);depthMap.minFilter=depthMap.magFilter=THREE.LinearFilter;depthMap.needsUpdate=true;
const waterMat=new THREE.ShaderMaterial({uniforms:{time:{value:0},depthMap:{value:depthMap},eye:{value:camera.position}},vertexShader:`varying vec3 world;void main(){world=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(world,1.);}`,fragmentShader:`uniform float time;uniform sampler2D depthMap;uniform vec3 eye;varying vec3 world;
void main(){vec2 p=world.xz;vec2 uv=p/4000.+.5;float depth=texture2D(depthMap,clamp(uv,0.,1.)).r*110.;if(abs(p.x)>1990.||abs(p.y)>1990.)depth=110.;
float a=p.x*.15+p.y*.09+time*.8;float b=p.x*.053-p.y*.13+time*.65;float c=p.x*.38+p.y*.31-time*1.2;
vec3 n=normalize(vec3(cos(a)*.1+cos(b)*.055+cos(c)*.025,1.,sin(a)*.065+sin(b)*.075));vec3 v=normalize(eye-world);float fres=pow(1.-max(dot(n,v),0.),4.);vec3 col=mix(vec3(.13,.65,.59),vec3(.025,.23,.32),smoothstep(0.,65.,depth));float rip=sin(a)*sin(b);col+=.012*rip;col=mix(col,vec3(.57,.76,.81),fres*.65);vec3 light=normalize(vec3(-.55,.8,.35));float spec=pow(max(dot(reflect(-light,n),v),0.),180.);col+=vec3(1.,.9,.69)*spec*.8;
float foam=(1.-smoothstep(.4,3.5,depth))*smoothstep(.3,.85,sin(depth*2.-time*1.3+sin(p.x*.09)+sin(p.y*.08))*.5+.5);col=mix(col,vec3(.83,.9,.82),foam*.72);float fog=1.-exp(-length(eye-world)*.00014);col=mix(col,vec3(.61,.77,.79),fog);gl_FragColor=vec4(col,1.);}`});const water=new THREE.Mesh(new THREE.PlaneGeometry(26000,26000),waterMat);water.rotation.x=-Math.PI/2;water.position.y=.3;scene.add(water);
let seed=271;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};const matrix=new THREE.Object3D();
function instances(geometry,material,items){const m=new THREE.InstancedMesh(geometry,material,items.length);items.forEach((a,i)=>{matrix.position.set(a.x,a.y,a.z);matrix.rotation.set(a.rx||0,a.rot||0,a.rz||0);matrix.scale.set(a.sx,a.sy,a.sz);matrix.updateMatrix();m.setMatrixAt(i,matrix.matrix);if(a.color)m.setColorAt(i,new THREE.Color(a.color))});m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
const trunks=[],crowns=[],palms=[],palmTrunks=[],stones=[];
for(let i=0;i<18000;i++){const x=(rnd()-.5)*2600,z=(rnd()-.5)*2700-60,h=height(x,z),d=distance(x,z),slope=Math.hypot(height(x+5,z)-height(x-5,z),height(x,z+5)-height(x,z-5))/10;if(h<6||slope>1.1||h>360)continue;if(rnd()>.74)continue;const ht=14+rnd()*16,r=5+rnd()*7,rot=rnd()*6.28;if(h<32&&d<130&&rnd()<.65){palmTrunks.push({x,y:h+ht*.5,z,sx:1,sy:ht,sz:1,rot});palms.push({x,y:h+ht,z,sx:r*1.5,sy:r*1.5,sz:r*1.5,rot});continue;}if(d<45)continue;trunks.push({x,y:h+ht*.42,z,sx:1.1,sy:ht*.85,sz:1.1});for(let j=0;j<3;j++)crowns.push({x:x+(rnd()-.5)*r,y:h+ht-j*3,z:z+(rnd()-.5)*r,sx:r,sy:r*.7,sz:r,rot:rot+j,color:new THREE.Color().setHSL(.22+rnd()*.07,.38+rnd()*.22,.19+rnd()*.12)});}
instances(new THREE.CylinderGeometry(.5,.85,1,5),new THREE.MeshStandardMaterial({color:0x615541,roughness:1}),trunks.concat(palmTrunks));instances(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardMaterial({color:0xffffff,roughness:1}),crowns);
const frondPositions=[];for(let n=0;n<9;n++){let a=n*Math.PI*2/9;for(let j=0;j<6;j++){const point=(t,side)=>{let r=t*1.2,w=Math.sin(t*Math.PI)*.14*side;return [Math.cos(a)*r-Math.sin(a)*w,.22*Math.sin(t*Math.PI)-t*t*.38,Math.sin(a)*r+Math.cos(a)*w]};let t=j/6,u=(j+1)/6;frondPositions.push(...point(t,-1),...point(u,-1),...point(t,1),...point(t,1),...point(u,-1),...point(u,1));}}const palmGeo=new THREE.BufferGeometry();palmGeo.setAttribute('position',new THREE.Float32BufferAttribute(frondPositions,3));palmGeo.computeVertexNormals();instances(palmGeo,new THREE.MeshStandardMaterial({color:0x4e772c,roughness:1,side:THREE.DoubleSide}),palms);
for(let i=0;i<1700;i++){let x=(rnd()-.5)*2700,z=(rnd()-.5)*2800,h=height(x,z),d=distance(x,z);if(h< -1||h>230||d>100)continue;let r=3+rnd()*11;stones.push({x,y:h+r*.2,z,sx:r,sy:r*(.5+rnd()),sz:r*.8,rot:rnd()*6,rx:rnd(),color:new THREE.Color().setHSL(.12,.09,.35+rnd()*.12)})}instances(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardMaterial({color:0xffffff,roughness:1}),stones);
const presets={island:{p:[1700,1550,2350],t:[0,70,0]},bay:{p:[390,370,1240],t:[-100,80,-270]},shore:{p:[-450,75,550],t:[-750,35,180]}};let transition=null;
function preset(name,immediate=false){const v=presets[name];document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));if(immediate){camera.position.fromArray(v.p);controls.target.fromArray(v.t);controls.update()}else transition={p:new THREE.Vector3(...v.p),t:new THREE.Vector3(...v.t)};}
preset('island',true);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>preset(b.dataset.view));controls.addEventListener('start',()=>{transition=null;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed','false'))});
let hidden=false;function toggleUI(){hidden=!hidden;document.querySelector('header').style.display=hidden?'none':'';document.querySelector('footer').style.display=hidden?'none':'';}document.querySelector('#hide').onclick=toggleUI;addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')toggleUI();if(e.key==='Escape'&&hidden)toggleUI()});
const ray=new THREE.Raycaster();renderer.domElement.addEventListener('dblclick',e=>{ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);const hits=ray.intersectObjects([land,water]);if(hits.length){let t=hits[0].point;if(Math.abs(t.x)<1500&&Math.abs(t.z)<1600){const dir=camera.position.clone().sub(controls.target).normalize();transition={t:t.clone(),p:t.clone().addScaledVector(dir,Math.min(420,camera.position.distanceTo(controls.target)))}}}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();loading.hidden=false;loading.textContent='Graphics connection interrupted. Reload to return to the island.'});
let last=performance.now();function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-last)/1000,.06);last=now;if(transition){let t=1-Math.exp(-dt*4);camera.position.lerp(transition.p,t);controls.target.lerp(transition.t,t);if(camera.position.distanceTo(transition.p)<.3)transition=null;}controls.target.x=clamp(controls.target.x,-1550,1550);controls.target.z=clamp(controls.target.z,-1600,1700);controls.target.y=Math.max(0,controls.target.y);controls.update();camera.position.y=Math.max(camera.position.y,height(camera.position.x,camera.position.z)+20,12);waterMat.uniforms.time.value=now*.001;sky.position.copy(camera.position);renderer.render(scene,camera)}requestAnimationFrame(frame);loading.hidden=true;
}
